### ISSUE TITLE
Parse and process custom 'ext' attributes

### ISSUE THREAD

**Issue by filip26** [filip26/alps#19]
**Describe the bug**
A custom attribute on 'ext' element is ignored, but should be parsed and processed as a custom attribute.

**To Reproduce**
```json
    "ext": [
      {
        "type": "metadata",
        "id": "title",
        "name": "title",
        "value": "Company API",
        "tags": "oas"
      },
      {
        "type": "metadata",
        "id": "id",
        "name": "id",
        "value": "http://alps.io/profiles/mamund/company",
        "tags": "oas"
      },
      {
        "type": "metadata",
        "id":"root",
        "name": "root",
        "value": "http://api.example.org/company",
        "tags": "oas"
      }
    ]
```
`name`, `type` and `tags` are ignored

**Expected behavior**
`name`, `type` and `tags` should be parsed and processed as custom attributes

**Comment by mamund** [comment]
yep. `name`, `type`, and `tags` in this example. any other custom properties should also be parsed and processed.

to dig a bit deeper here:

i forsee a challenge in "nesting" objects with EXT elements. 

one way to do this would be to say the only valid child element of EXT is another EXT:

```
<ext id="person" type="semantic">
  <ext id="docs" value="Special profile object for typical person in our group" />
  <ext id="name" />
  <ext id="hatSize" />
  <ext href="http://alps.example.org/profiles/smart-person" />
</ext>
```

another approach would be to say that the only valid child elements of and EXT element are existing ALPS elements; for example, DOC, LINK, DESCRIPTOR and EXT.

so a valid rendering of the above example might be:

```
<ext id="person" type="semantic">
  <doc>Special profile object for typical person in our group</doc>
  <descriptor id="name" />
  <ext id="hatSize" />
  <link id="http://alps.example.org/profiles/smart-person" />
</ext>
```

finally, you might consider supporting an arbitrary block of content within an EXT:

```
<ext id="person" schema="http://schema.examples.org/person">
  <story>Special profile object for typical person in our group</story>
  <property>name</property>
  <property>hatSize</property>
  <external id="http://alps.example.org/profiles/smart-person" />
</ext>
```

this last example is essentially creating an "island" of arbitrary content (supported by a direct schema link). i suspect this is going a bit too far and is not really needed. although the possibliity of a schema reference for EXT elements might not be a bad idea.

open for thoughts.

**Comment by filip26** [comment]
The nesting is real challenge, especially when considering transformations between representations. I'm thinking about splitting this issue into two, one related to custom attributes and the second one to the nested content.

**Comment by filip26** [comment]
Perhaps, there should be a strict definition of a custom attribute. See this example:

```json
"ext":  {
        "id": "id",
        "custom1": {
              "a": false,
              "b": 123
         },
        "custom2": {
        }
      }
```
How does the `HTML` representation of the example look like?

```xml
<ext id="id" custom1:a="false" custom1:b="123" custom2/>
```
or
```xml
<ext id="id">
   <custom1>...</custom1>
   <custom2/>
</ext>
```

**Comment by mamund** [comment]
yeah - it's messy!

i prefer the second XML rendering of the sample JSON:
```
<ext id="id">
   <custom1 a="false" b="123"/>
   <custom2/>
</ext>
```
just taste here, i think. not sure there is much precedent for this view.  but i also think that approch will make parsing and transforming easier in the long run (think XML->JSON), right?

if we support the example I selected here, maybe we also need to intoduce the `schema` property? IOW, if you want to control the layout inside the EXT block, you do it using schema(s).  i see trouble ahead since we'll likely need more than one schema now (XSD, JSONSchema, and ???YAML) -- sheesh!

so, maybe you're point of only supporting scalars is a better angle. if we allow support for nested EXT elements, that gives quite a bit of options w/o complicating parsing/transforming.

thoughts?

**Comment by filip26** [comment]
`XML` attributes are scalars, just string values. `JSON` does not have a concept of attributes but in the examples I see only scalar values as 'ext' object properties.  

As you pointed out, the nested content and its mapping to `JSON`, `YAML` is quite tricky. It might require a schema, etc. 

If you agree then I will close this issue by supporting only scalars. It does the job for the current examples and we can go back to the nested content, non-scalars values, when solving issue #22 .

**Comment by mamund** [comment]
agreed.

EXT is for scalars only but let's be sure we can support arbitrary attributes on the XML side like this:

```
<ext id="hatSize" type="fedora" name="homburg" color="black">12.5</xml>
```
and the JSON would then be:

```
{"ext" : {"id" : "hatSize", "type" : "fedora", "name" : "homburg", "color" : "black", "value" : "12.5" } }
```

note that i serialized the value as a string, not a number of bool. if we want to be able to do that, we'll need to add a property to the EXT to carry that. I prefer *NOT* using `type` for this since we use `type` for a wider range of values already. 

i like `scalar` to hold the strong-typing hint. open to using others. the spec will be written that EXT:scalar is an OPTIONAL property and can be set to `string` `boolean`, or `number`. If the value is missing (or set to an invalid value) then the parser will treat `scalar` value as set to `string`.

does that work?

**Comment by filip26** [comment]
yes, it does. Actually I've implemented a support for numbers and boolean already (it's not committed yet) but the core model sticks with strings. Let's give it a try.

**Comment by filip26** [comment]
if there are no objections (@mamund ?) then I will close this issue. See PR #23 and issue #22

**Comment by mamund** [comment]
no objections. closing is fine.
